POST https://wsp.gemline.com/GemlineWebService/PO/v1/GemlinePOService.svc
Content-Type: text/xml;charset=UTF-8
SOAPAction: "sendPO"

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.promostandards.org/WSDL/PO/1.0.0/" xmlns:shar="http://www.promostandards.org/WSDL/PO/1.0.0/SharedObjects/">
    <soapenv:Header/>
    <soapenv:Body>
        <ns:SendPORequest>
            <shar:wsVersion>1.0.0</shar:wsVersion>
            <shar:id>3004775</shar:id>
            <shar:password>fE1oK6vB4eX8oC9i</shar:password>
            <ns:PO>
                <ns:orderType>?</ns:orderType>
                <ns:orderNumber>?</ns:orderNumber>
                <ns:orderDate>?</ns:orderDate>
                <!--Optional:-->
                <ns:lastModified>?</ns:lastModified>
                <ns:totalAmount>?</ns:totalAmount>
                <!--Optional:-->
                <ns:paymentTerms>?</ns:paymentTerms>
                <ns:rush>?</ns:rush>
                <shar:currency>?</shar:currency>
                <!--Optional:-->
                <shar:DigitalProof>
                    <shar:DigitalProofAddressArray>
                        <!--1 or more repetitions:-->
                        <shar:DigitalProofAddress>
                            <shar:type>?</shar:type>
                            <shar:email>?</shar:email>
                            <shar:lineItemGroupingId>?</shar:lineItemGroupingId>
                        </shar:DigitalProofAddress>
                    </shar:DigitalProofAddressArray>
                    <shar:required>?</shar:required>
                </shar:DigitalProof>
                <!--Optional:-->
                <ns:OrderContactArray>
                    <!--1 or more repetitions:-->
                    <shar:Contact>
                        <!--Optional:-->
                        <shar:accountName>?</shar:accountName>
                        <!--Optional:-->
                        <shar:accountNumber>?</shar:accountNumber>
                        <shar:contactType>?</shar:contactType>
                        <shar:ContactDetails>
                            <!--Optional:-->
                            <shar:attentionTo>?</shar:attentionTo>
                            <!--Optional:-->
                            <shar:companyName>?</shar:companyName>
                            <!--Optional:-->
                            <shar:address1>?</shar:address1>
                            <!--Optional:-->
                            <shar:address2>?</shar:address2>
                            <!--Optional:-->
                            <shar:address3>?</shar:address3>
                            <!--Optional:-->
                            <shar:city>?</shar:city>
                            <!--Optional:-->
                            <shar:region>?</shar:region>
                            <!--Optional:-->
                            <shar:postalCode>?</shar:postalCode>
                            <!--Optional:-->
                            <shar:country>?</shar:country>
                            <!--Optional:-->
                            <shar:email>?</shar:email>
                            <!--Optional:-->
                            <shar:phone>?</shar:phone>
                            <!--Optional:-->
                            <shar:comments>?</shar:comments>
                        </shar:ContactDetails>
                    </shar:Contact>
                </ns:OrderContactArray>
                <ns:ShipmentArray>
                    <!--1 or more repetitions:-->
                    <shar:Shipment>
                        <!--0 to 2 repetitions:-->
                        <shar:shipReferences>?</shar:shipReferences>
                        <!--Optional:-->
                        <shar:comments>?</shar:comments>
                        <!--Optional:-->
                        <shar:ThirdPartyAccount>
                            <shar:accountName>?</shar:accountName>
                            <shar:accountNumber>?</shar:accountNumber>
                            <shar:ContactDetails>
                                <!--Optional:-->
                                <shar:attentionTo>?</shar:attentionTo>
                                <!--Optional:-->
                                <shar:companyName>?</shar:companyName>
                                <!--Optional:-->
                                <shar:address1>?</shar:address1>
                                <!--Optional:-->
                                <shar:address2>?</shar:address2>
                                <!--Optional:-->
                                <shar:address3>?</shar:address3>
                                <!--Optional:-->
                                <shar:city>?</shar:city>
                                <!--Optional:-->
                                <shar:region>?</shar:region>
                                <!--Optional:-->
                                <shar:postalCode>?</shar:postalCode>
                                <!--Optional:-->
                                <shar:country>?</shar:country>
                                <!--Optional:-->
                                <shar:email>?</shar:email>
                                <!--Optional:-->
                                <shar:phone>?</shar:phone>
                                <!--Optional:-->
                                <shar:comments>?</shar:comments>
                            </shar:ContactDetails>
                        </shar:ThirdPartyAccount>
                        <shar:allowConsolidation>?</shar:allowConsolidation>
                        <shar:blindShip>?</shar:blindShip>
                        <shar:packingListRequired>?</shar:packingListRequired>
                        <shar:FreightDetails>
                            <shar:carrier>?</shar:carrier>
                            <shar:service>?</shar:service>
                        </shar:FreightDetails>
                        <shar:ShipTo>
                            <shar:customerPickup>?</shar:customerPickup>
                            <shar:ContactDetails>
                                <!--Optional:-->
                                <shar:attentionTo>?</shar:attentionTo>
                                <!--Optional:-->
                                <shar:companyName>?</shar:companyName>
                                <!--Optional:-->
                                <shar:address1>?</shar:address1>
                                <!--Optional:-->
                                <shar:address2>?</shar:address2>
                                <!--Optional:-->
                                <shar:address3>?</shar:address3>
                                <!--Optional:-->
                                <shar:city>?</shar:city>
                                <!--Optional:-->
                                <shar:region>?</shar:region>
                                <!--Optional:-->
                                <shar:postalCode>?</shar:postalCode>
                                <!--Optional:-->
                                <shar:country>?</shar:country>
                                <!--Optional:-->
                                <shar:email>?</shar:email>
                                <!--Optional:-->
                                <shar:phone>?</shar:phone>
                                <!--Optional:-->
                                <shar:comments>?</shar:comments>
                            </shar:ContactDetails>
                            <shar:shipmentId>?</shar:shipmentId>
                        </shar:ShipTo>
                    </shar:Shipment>
                </ns:ShipmentArray>
                <ns:LineItemArray>
                    <!--1 or more repetitions:-->
                    <ns:LineItem>
                        <ns:lineNumber>?</ns:lineNumber>
                        <!--Optional:-->
                        <ns:lineReferenceId>?</ns:lineReferenceId>
                        <shar:description>?</shar:description>
                        <ns:lineType>?</ns:lineType>
                        <!--Optional:-->
                        <shar:Quantity>
                            <shar:uom>?</shar:uom>
                            <shar:value>?</shar:value>
                        </shar:Quantity>
                        <!--Optional:-->
                        <shar:fobId>?</shar:fobId>
                        <shar:ToleranceDetails>
                            <!--Optional:-->
                            <shar:uom>?</shar:uom>
                            <!--Optional:-->
                            <shar:value>?</shar:value>
                            <shar:tolerance>?</shar:tolerance>
                        </shar:ToleranceDetails>
                        <ns:allowPartialShipments>?</ns:allowPartialShipments>
                        <!--Optional:-->
                        <shar:unitPrice>?</shar:unitPrice>
                        <ns:lineItemTotal>?</ns:lineItemTotal>
                        <!--Optional:-->
                        <ns:requestedShipDate>?</ns:requestedShipDate>
                        <!--Optional:-->
                        <ns:requestedInHandsDate>?</ns:requestedInHandsDate>
                        <!--Optional:-->
                        <ns:referenceSalesQuote>?</ns:referenceSalesQuote>
                        <!--Optional:-->
                        <shar:Program>
                            <!--Optional:-->
                            <shar:id>?</shar:id>
                            <!--Optional:-->
                            <shar:name>?</shar:name>
                        </shar:Program>
                        <!--Optional:-->
                        <ns:endCustomerSalesOrder>?</ns:endCustomerSalesOrder>
                        <!--Optional:-->
                        <shar:productId>?</shar:productId>
                        <!--Optional:-->
                        <ns:customerProductId>?</ns:customerProductId>
                        <!--Optional:-->
                        <shar:lineItemGroupingId>?</shar:lineItemGroupingId>
                        <!--Optional:-->
                        <ns:PartArray>
                            <!--1 or more repetitions:-->
                            <shar:Part>
                                <!--Optional:-->
                                <shar:partGroup>?</shar:partGroup>
                                <shar:partId>?</shar:partId>
                                <!--Optional:-->
                                <shar:customerPartId>?</shar:customerPartId>
                                <shar:customerSupplied>?</shar:customerSupplied>
                                <!--Optional:-->
                                <shar:description>?</shar:description>
                                <shar:Quantity>
                                    <shar:uom>?</shar:uom>
                                    <shar:value>?</shar:value>
                                </shar:Quantity>
                                <!--Zero or more repetitions:-->
                                <shar:locationLinkId>?</shar:locationLinkId>
                                <!--Optional:-->
                                <shar:unitPrice>?</shar:unitPrice>
                                <!--Optional:-->
                                <shar:extendedPrice>?</shar:extendedPrice>
                                <!--Optional:-->
                                <shar:ShipmentLinkArray>
                                    <!--1 or more repetitions:-->
                                    <shar:ShipmentLink>
                                        <shar:Quantity>
                                            <shar:uom>?</shar:uom>
                                            <shar:value>?</shar:value>
                                        </shar:Quantity>
                                        <shar:shipmentId>?</shar:shipmentId>
                                    </shar:ShipmentLink>
                                </shar:ShipmentLinkArray>
                            </shar:Part>
                        </ns:PartArray>
                        <!--Optional:-->
                        <shar:Configuration>
                            <!--Optional:-->
                            <shar:ChargeArray>
                                <!--1 or more repetitions:-->
                                <shar:Charge>
                                    <!--Optional:-->
                                    <shar:chargeName>?</shar:chargeName>
                                    <!--Optional:-->
                                    <shar:description>?</shar:description>
                                    <!--Optional:-->
                                    <shar:extendedPrice>?</shar:extendedPrice>
                                    <!--Optional:-->
                                    <shar:unitPrice>?</shar:unitPrice>
                                    <shar:chargeId>?</shar:chargeId>
                                    <shar:chargeType>?</shar:chargeType>
                                    <shar:Quantity>
                                        <shar:uom>?</shar:uom>
                                        <shar:value>?</shar:value>
                                    </shar:Quantity>
                                </shar:Charge>
                            </shar:ChargeArray>
                            <!--Optional:-->
                            <shar:LocationArray>
                                <!--1 or more repetitions:-->
                                <shar:Location>
                                    <!--Optional:-->
                                    <shar:locationName>?</shar:locationName>
                                    <shar:DecorationArray>
                                        <!--1 or more repetitions:-->
                                        <shar:Decoration>
                                            <!--Optional:-->
                                            <shar:decorationName>?</shar:decorationName>
                                            <shar:Artwork>
                                                <!--Optional:-->
                                                <shar:instructions>?</shar:instructions>
                                                <!--Optional:-->
                                                <shar:refArtworkId>?</shar:refArtworkId>
                                                <!--Optional:-->
                                                <shar:totalStitchCount>?</shar:totalStitchCount>
                                                <!--Optional:-->
                                                <shar:ArtworkFileArray>
                                                    <!--1 or more repetitions:-->
                                                    <shar:ArtworkFile>
                                                        <shar:artworkType>?</shar:artworkType>
                                                        <shar:fileLocation>?</shar:fileLocation>
                                                        <shar:fileName>?</shar:fileName>
                                                        <shar:transportMechanism>?</shar:transportMechanism>
                                                    </shar:ArtworkFile>
                                                </shar:ArtworkFileArray>
                                                <!--Optional:-->
                                                <shar:description>?</shar:description>
                                                <!--Optional:-->
                                                <shar:Dimensions>
                                                    <!--Optional:-->
                                                    <shar:diameter>?</shar:diameter>
                                                    <!--Optional:-->
                                                    <shar:height>?</shar:height>
                                                    <!--Optional:-->
                                                    <shar:uom>?</shar:uom>
                                                    <!--Optional:-->
                                                    <shar:width>?</shar:width>
                                                    <shar:useMaxLocationDimensions>?</shar:useMaxLocationDimensions>
                                                    <shar:geometry>?</shar:geometry>
                                                </shar:Dimensions>
                                                <!--Optional:-->
                                                <shar:Layers>
                                                    <shar:colorSystem>?</shar:colorSystem>
                                                    <shar:LayerOrStopArray>
                                                        <!--1 or more repetitions:-->
                                                        <shar:LayerOrStop>
                                                            <shar:color>?</shar:color>
                                                            <shar:nameOrNumber>?</shar:nameOrNumber>
                                                            <shar:description>?</shar:description>
                                                        </shar:LayerOrStop>
                                                    </shar:LayerOrStopArray>
                                                </shar:Layers>
                                                <!--Optional:-->
                                                <shar:TypesetArray>
                                                    <!--1 or more repetitions:-->
                                                    <shar:Typeset>
                                                        <!--Optional:-->
                                                        <shar:fontSize>?</shar:fontSize>
                                                        <!--Optional:-->
                                                        <shar:font>?</shar:font>
                                                        <shar:sequenceNumber>?</shar:sequenceNumber>
                                                        <shar:value>?</shar:value>
                                                    </shar:Typeset>
                                                </shar:TypesetArray>
                                            </shar:Artwork>
                                            <shar:decorationId>?</shar:decorationId>
                                        </shar:Decoration>
                                    </shar:DecorationArray>
                                    <shar:locationLinkId>?</shar:locationLinkId>
                                    <shar:locationId>?</shar:locationId>
                                </shar:Location>
                            </shar:LocationArray>
                            <!--Optional:-->
                            <shar:referenceNumberType>?</shar:referenceNumberType>
                            <!--Optional:-->
                            <shar:referenceNumber>?</shar:referenceNumber>
                            <shar:preProductionProof>?</shar:preProductionProof>
                        </shar:Configuration>
                    </ns:LineItem>
                </ns:LineItemArray>
                <ns:termsAndConditions>?</ns:termsAndConditions>
                <!--Optional:-->
                <ns:salesChannel>?</ns:salesChannel>
                <!--Optional:-->
                <ns:promoCode>?</ns:promoCode>
                <!--Optional:-->
                <ns:TaxInformationArray>
                    <!--1 or more repetitions:-->
                    <shar:TaxInformation>
                        <!--1 or more repetitions:-->
                        <shar:taxJurisdiction>?</shar:taxJurisdiction>
                        <shar:taxExempt>?</shar:taxExempt>
                        <shar:taxId>?</shar:taxId>
                        <shar:taxType>?</shar:taxType>
                        <!--Optional:-->
                        <shar:taxAmount>?</shar:taxAmount>
                    </shar:TaxInformation>
                </ns:TaxInformationArray>
            </ns:PO>
        </ns:SendPORequest>
    </soapenv:Body>
</soapenv:Envelope>