POST https://wsd.gemline.com/GemlineWebService/OrderStatus/v1/GemlineOrderStatusService.svc
Content-Type: text/xml;charset=UTF-8
SOAPAction: "getOrderStatusDetails"

// seems like if we don't express the referenceNumber we get
// a list of all orders we have w/ Gemline?


<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/">
    <soapenv:Header/>
    <soapenv:Body>
        <ns:GetOrderStatusDetailsRequest>
            <ns:wsVersion>1.0.0</ns:wsVersion>
            <ns:id>3004775</ns:id>
            <ns:password>fE1oK6vB4eX8oC9i</ns:password>
            <ns:queryType>2</ns:queryType>
            <!--Optional:-->
            <ns:referenceNumber>1000001</ns:referenceNumber>
            <ns:statusTimeStamp>2025-06-04T09:30:00</ns:statusTimeStamp>
        </ns:GetOrderStatusDetailsRequest>
    </soapenv:Body>
</soapenv:Envelope>
