POST https://psosn100-stg.pcna.online/psOsn.svc
Content-Type: text/xml;charset=UTF-8
SOAPAction: "getOrderShipmentNotification"

// seems like if we don't express the referenceNumber we get
// a list of all orders we have w/ PCNA?

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.promostandards.org/WSDL/OrderShipmentNotificationService/1.0.0/" xmlns:shar="http://www.promostandards.org/WSDL/OrderShipmentNotificationService/1.0.0/SharedObjects/">
    <soapenv:Header/>
    <soapenv:Body>
        <ns:GetOrderShipmentNotificationRequest>
            <ns:wsVersion>1.0.0</ns:wsVersion>
            <!--Optional:-->
            <ns:id>Moo</ns:id>
            <!--Optional:-->
            <ns:password>r_zyel0OyUn*g.=@8TCZ>ve}+R4+q1C(w!.UIs.WMOYhmio}9LG>RFJeX+>*3dE</ns:password>
            <ns:queryType>1</ns:queryType>
            <ns:referenceNumber>moo-test-order-21</ns:referenceNumber>
            <!--Optional:-->

        </ns:GetOrderShipmentNotificationRequest>
    </soapenv:Body>
</soapenv:Envelope>