POST https://psorderstatus100-stg.pcna.online/psOrderStatus.svc
Content-Type: text/xml;charset=UTF-8
SOAPAction: "getOrderStatusDetails"



// seems like if we don't express the referenceNumber we get
// a list of all orders we have w/ PCNA?

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.promostandards.org/WSDL/OrderStatusService/1.0.0/">
    <soapenv:Header/>
    <soapenv:Body>
        <ns:GetOrderStatusDetailsRequest>
            <!--Optional:-->
            <ns:wsVersion>1.0.0</ns:wsVersion>
            <!--Optional:-->
            <ns:id>Moo</ns:id>
            <!--Optional:-->
            <ns:password>r_zyel0OyUn*g.=@8TCZ>ve}+R4+q1C(w!.UIs.WMOYhmio}9LG>RFJeX+>*3dE</ns:password>
            <ns:queryType>3</ns:queryType>

<!--            <ns:referenceNumber>100-test-2</ns:referenceNumber>-->
<!--            <ns:statusTimeStamp>2025-06-04T09:30:00</ns:statusTimeStamp>-->

        </ns:GetOrderStatusDetailsRequest>
    </soapenv:Body>
</soapenv:Envelope>

